# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBook', '0004_location_media_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='prenotation',
            name='check_in',
            field=models.DateTimeField(verbose_name='check_in date'),
        ),
        migrations.AlterField(
            model_name='prenotation',
            name='check_out',
            field=models.DateTimeField(verbose_name='check_out date'),
        ),
        migrations.AlterField(
            model_name='roomwaitinglist',
            name='check_in_waitinglist',
            field=models.DateTimeField(verbose_name='check_in date'),
        ),
        migrations.AlterField(
            model_name='roomwaitinglist',
            name='check_out_waitinglist',
            field=models.DateTimeField(verbose_name='check_out date'),
        ),
    ]
